# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='name',
            field=models.CharField(max_length=50, verbose_name='花型名称'),
        ),
    ]
